# Generated by Django 3.1.2 on 2022-05-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('date_emission', models.DateField()),
                ('reference', models.TextField(blank=True)),
                ('origine', models.CharField(max_length=100)),
                ('objet', models.TextField(blank=True)),
                ('bureau', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourrierDepart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('date_emission', models.DateField()),
                ('reference', models.TextField(blank=True)),
                ('origine', models.CharField(max_length=100)),
                ('objet', models.TextField(blank=True)),
                ('bureau', models.TextField(max_length=100)),
            ],
        ),
    ]
