# Generated by Django 3.1.2 on 2022-05-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourriersApp', '0002_courrier_supprimer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courrier',
            name='supprimer',
        ),
    ]
