# Generated by Django 3.1.2 on 2022-05-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourriersApp', '0004_bureau_courrierdepart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courrierdepart',
            table='courriersapp_courrierdepart',
        ),
    ]
