# Generated by Django 3.1.2 on 2022-05-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourriersApp', '0005_auto_20220512_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='bureau',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courrierdepart',
            name='bureau',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='courrierdepart',
            table=None,
        ),
        migrations.DeleteModel(
            name='Bureau',
        ),
    ]
