# Generated by Django 3.1.2 on 2022-05-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourriersApp', '0006_auto_20220516_1202'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courrier',
            table='courriers',
        ),
        migrations.AlterModelTable(
            name='courrierdepart',
            table='courriersdepart',
        ),
    ]
